# Generated by Django 4.1.7 on 2023-08-28 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='beer',
            name='name',
            field=models.CharField(default='Test', max_length=255),
            preserve_default=False,
        ),
    ]
